### ISSUE TITLE
Responsive formatting toolbar

### ISSUE THREAD

**Issue by prologic** [jointwt/goryon#79]
The toolbar for formatting and media upload functionality right now is a poor experience for users. I've noticed (_in the real world watching friend/family/etc_) use this struggle to find the button to upload an image/photo.

A more responsive toolbar would be ideal here, but I'm not sure what options are available in Flutter to help with this?

**Comment by aaadonai** [comment]
I managed do a work around for this issue. What I really want to do was to move the toolbar to the left, closer to the edge of the screen, aligned with the avatar. But I don't know enough of Flutter to do it. So instead I just rearranged the buttons, moved the link and upload button to the begin of the toolbar and left the bold, strike-through to the end. Since striker-through is less used it will be less of a struggle to users.
Before
![Screen Shot 2021-05-09 at 7 26 12 pm](https://user-images.githubusercontent.com/1087949/117603614-6f4b6980-b108-11eb-9528-62af314a4266.png)
After
![Screen Shot 2021-05-09 at 8 52 34 pm](https://user-images.githubusercontent.com/1087949/117603662-8722ed80-b108-11eb-9a78-8337761f66b4.png)
